config/routes.rb
Rails.application.routes.draw do

  resources :colores

  resources :roles

  resources :user_sessions
  resources :users

  get 'login' => 'user_sessions#new', :as => :login
  get 'logout' => 'user_sessions#destroy', :as => :logout

  resources :articulos

  resources :videos

  resources :images

  resources :telas

  resources :telas do
    resources :images
  end
  
  resources :telas do
    resources :colores
  end

  resources :bases_telas

  resources :acabados

  resources :proveedores

  resources :clasificaciones

  get 'sofcartej/inicio'

  get 'sofcartej/sofcartej'

  get 'sofcartej/contacto'
  
  get 'sofcartej/pru'

  resources :tipos_telas

  resources :usos

  root 'sofcartej#inicio'

end

app/models/acabado.rb
class Acabado < ActiveRecord::Base
	has_many :telas
	validates :nombre, presence: true


  def self.ransackable_attributes(auth_object = nil)
    super - ['id', 'created_at', 'updated_at']
  end
  
  def self.search(search, page)
		where(['upper(nombre) like ?',
		"%#{search}%".upcase]).paginate(page: page, per_page: 7).order("id")
	end
end

app/models/articulo.rb
class Articulo < ActiveRecord::Base
	has_attached_file :arti, :default_url => "/articulos"
  	do_not_validate_attachment_file_type :arti
  	validates :titulo, presence: true
  	validates :arti, presence: true
end

app/models/bases_tela.rb
class BasesTela < ActiveRecord::Base
  belongs_to :clasificacione
  has_many :telas
  validates :nombre, presence: true
  def self.ransackable_attributes(auth_object = nil)
    super - ['id', 'created_at', 'updated_at']
  end
  
  	def self.search(search, page)
		where(['upper(nombre) like ?',
		"%#{search}%".upcase]).paginate(page: page, per_page: 7).order("id")
	end
end

app/models/clasificacione.rb
class Clasificacione < ActiveRecord::Base
	has_many :bases_telas
  belongs_to :tiposTela
	validates :nombre, presence: true


end

app/models/colore.rb
class Colore < ActiveRecord::Base
  belongs_to :tela
   validates :img, presence: true
   validates :cantidadActual, presence: true
   validates :color, presence: true
   validates :cantidadActual, :numericality => { :greater_than_or_equal_to => 0 }
   validates :entrada, :numericality => { :greater_than_or_equal_to => 0 }
   validates :salida, :numericality => { :greater_than_or_equal_to => 0 }
   has_attached_file :img
  do_not_validate_attachment_file_type :img
end

app/models/image.rb
class Image < ActiveRecord::Base
  validates :imagen, :attachment_presence => true
  belongs_to :tela
   has_attached_file :imagen
  do_not_validate_attachment_file_type :imagen
end

app/models/proveedore.rb
class Proveedore < ActiveRecord::Base
	has_many :telas
	validates :nombre, presence: true
	validates :correo, presence: true

   VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
    validates :correo, format: { :with => VALID_EMAIL_REGEX , message: "El formato del correo es invalido" }

  def self.ransackable_attributes(auth_object = nil)
    super - ['id', 'created_at', 'updated_at']
  end
end

app/models/role.rb
class Role < ActiveRecord::Base
end

app/models/tela.rb
class Tela < ActiveRecord::Base
  # attr_accessible :nombre, :tiposTela, :basesTela, :proveedore, :referenciasComerciale, :composicion, :anchoOrillo, :uso, :acabado, :peso, :pesoUnidad, :fichaTecnica, :document

  validates :nombre, presence: true
  validates :codigo, presence: true
  validates :composicion, presence: true
  validates :basesTela, presence: true
  validates :proveedore, presence: true
  validates :nombrecomercial, presence: true
  validates :anchoOrillo, presence: true
  validates :uso, presence: true
  validates :acabado, presence: true
  validates :pesoUnidad, presence: true
  validates :peso, presence: true
  validates :tejido, presence: true

  belongs_to :basesTela
  belongs_to :proveedore
  belongs_to :uso
  belongs_to :acabado
  has_many :images, :dependent => :destroy
  has_many :colores, :dependent => :destroy


  has_attached_file :document, :default_url => "/telas"
  do_not_validate_attachment_file_type :document
	
  def self.to_csv(options = {})
	  CSV.generate(options) do |csv|
	    csv << column_names
	    all.each do |tela|
	      csv << tela.attributes.values_at(*column_names)
	    end
	  end
	end
	
	#Metodo para el buscador multiple, los siguietes atributos no seran visibles en la vista del usuario
	#ya que no son necesarios.
	def self.ransackable_attributes(auth_object = nil)
    super - ['id', 'created_at', 'updated_at', 
      'tiposTela_id', 'basesTela_id', 'proveedore_id', 'referenciasComerciale_id',
      'uso_id', 'acabado_id', 'fichaTecnica', 'document_file_name',
      'document_content_type', 'document_file_size', 'document_updated_at', 'datos','clasificacione_id']
  end

end

app/models/tipos_tela.rb
class TiposTela < ActiveRecord::Base
	has_many :telas
	has_many :clasificaciones

  def self.ransackable_attributes(auth_object = nil)
    super - ['id', 'created_at', 'updated_at']
  end
end

app/models/user.rb
class User < ActiveRecord::Base
	authenticates_with_sorcery!
	validates :password, length: { minimum: 3 }
    validates :password, confirmation: true
    validates :password_confirmation, presence: true
    validates :nombre, presence: true
    validates :email, uniqueness: true
    validates :email, presence: true
    VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
    validates :email, format: { :with => VALID_EMAIL_REGEX , message: "El formato del correo es invalido" }
    validates :nombre, length: { in: 4..15 }

    has_attached_file :foto, :default_url => "/users"
  	do_not_validate_attachment_file_type :foto

  	def self.search(search, page)
	  where(['nombre LIKE :s OR email LIKE :s', :s => 
	    "%#{search}%".upcase]).paginate(page: page, per_page: 5).order("nombre")
	end
end

app/models/uso.rb
class Uso < ActiveRecord::Base
	has_many :telas
	validates :nombre, presence: true


	
  	def self.search(search, page)
		where(['upper(nombre) like ?',
		"%#{search}%".upcase]).paginate(page: page, per_page: 7).order("id")
	end
  
end

app/models/video.rb
class Video < ActiveRecord::Base
	validates :vid, presence: true
	validates :titulo, presence: true
  has_attached_file :vid
  do_not_validate_attachment_file_type :vid

  	def self.search(search, page)
		where(['upper(titulo) like ?',
		"%#{search}%".upcase]).paginate(page: page, per_page: 2).order("id")
	end
end

app/controllers/bases_telas_controller.rb
class BasesTelasController < ApplicationController
  before_action :set_bases_tela, only: [:show, :edit, :update, :destroy]

  # GET /bases_telas
  # GET /bases_telas.json
  def index
    @bases_telas = BasesTela.search(params[:search], params[:page])
  end
  # GET /bases_telas/1
  # GET /bases_telas/1.json
  def show
  end

  # GET /bases_telas/new
  def new
    @bases_tela = BasesTela.new
  end

  # GET /bases_telas/1/edit
  def edit
  end

  # POST /bases_telas
  # POST /bases_telas.json
  def create
    @bases_tela = BasesTela.new(bases_tela_params)
    render action: :new unless @bases_tela.save

  end

  # PATCH/PUT /bases_telas/1
  # PATCH/PUT /bases_telas/1.json
  def update
     render action: :edit unless @bases_tela.update_attributes(bases_tela_params)
  end

  # DELETE /bases_telas/1
  # DELETE /bases_telas/1.json
  def destroy
    @bases_tela.destroy
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_bases_tela
      @bases_tela = BasesTela.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def bases_tela_params
      params.require(:bases_tela).permit(:clasificacione_id, :nombre)
    end
end

app/helpers/acabados_helper.rb
module AcabadosHelper
end

app/helpers/bases_telas_helper.rb
module BasesTelasHelper
end

app/helpers/colores_helper.rb
module ColoresHelper
    
    def operacion(act,ent,sal)
        
        res = act + ent
        resp = res - sal
        rest = resp/5
      " <strong class='valorc'> #{ resp }  Mts</strong><div class='progress progress-striped active'>
        <div class='progress-bar progress-bar-info' style='width: #{rest}%'></div>
        </div>".html_safe
      
    end
end

app/helpers/images_helper.rb
module ImagesHelper
end

app/helpers/roles_helper.rb
module RolesHelper
end

app/helpers/telas_helper.rb
module TelasHelper
end

app/helpers/users_helper.rb
module UsersHelper
	def mostrar(ro)
		if ro == 1
			'<span class="label label-primary">Administrador</span>'.html_safe
		else 
			'<span class="label label-default">Usurio</span>'.html_safe
		end
	end
end

app/helpers/usos_helper.rb
module UsosHelper
end

app/helpers/videos_helper.rb
module VideosHelper
end

app/views/bases_telas/_bases_tela.html.erb
<tr>
        <td><%= bases_tela.clasificacione.nombre %></td>
        <td><%= bases_tela.nombre.capitalize %></td>
         <td>
          <div class="btn-group">
            <a href="#"> </a>
            <ul class="list-inline">
              <li> <%= link_to '<button class="btn btn-primary"> <i class="fa fa-wrench neg"></i> Editar</button>'.html_safe, edit_bases_tela_path(bases_tela), remote: true %></li>
              <li> <%= link_to '<button class="btn btn-danger"><i class="fa fa-times neg"></i> Eliminar</button>'.html_safe, bases_tela, method: :delete, data: { confirm: 'Estas segur@?' }, remote: true%></li>
            </ul>
          </div>
        </td>
      </tr>

app/views/bases_telas/_form.html.erb
<%= simple_form_for(@bases_tela, :html => { :class => 'form-horizontal', remote: true } ) do |f| %>
  <% if @bases_tela.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@bases_tela.errors.count, "error") %> prohibited this bases_tela from being saved:</h2>

      <ul>
      <% @bases_tela.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
   <label>Clasificación</label><br>
    <%= f.collection_select :clasificacione_id, Clasificacione.all, :id, :nombre, class: "form-control", prompt: "Seleccione clasificación" %>
  </div>
  <div class="field">
    <%= f.label :nombre %><br>
    <%= f.text_field :nombre %>
  </div>
  <div class="actions">
    <%= f.submit "Guardar", class: "btn btn-success" %>
  </div>
<% end %>

app/views/bases_telas/_show.html.erb
<div class="bases_tela">
	

	<p>
	  <strong>Clasificacione:</strong>
	  <%= @bases_tela.clasificacione.nombre %>
	</p>

	<p>
	  <strong>Nombre:</strong>
	  <%= @bases_tela.nombre %>
	</p>

</div>

app/views/bases_telas/_usuario.html.erb
<div class="separa">
  <center><h3>Bases</h3></center>
  <div class="divsof">
  <table class="table table-hover table-heading">
    <thead>
      <tr>
        <th class="cen">Nombre de la base</th>
      </tr>
    </thead>

    <tbody>
    <% @bases_telas.each do |a| %>
      <tr>
          <td><%= a.nombre.capitalize %></td>
      </tr>
    <% end %>
    </tbody>
  </table>
  </div>
</div>

app/views/bases_telas/index.html.erb
<% if current_user.role_id == 1 %>
<center>
  <div class="bani">
  <h1 class="banih slideDown">Bases</h1>
  <%= image_tag("banner.jpg", class: "banii slideDown") %>
  <p class="banip slideDown"><br>Bases que se le pueden dar a las telas en sofcartej, con la clasificacion.</p>
</div>
<div class="convi2">
  <%= form_tag bases_telas_path, :method => 'get' do %>
    <% content_tag :label do %>
      Buscar por nombre:
      <%= text_field_tag :search, params[:search] %>
      <%= submit_tag "Buscar", :name => nil %>
    <% end %>
  <% end %>
<div class="conpa">
  <span class="label gran"><%= will_paginate @bases_telas, :previous_label => '<span class="label label-success gran">← Anterior</span>'.html_safe, :next_label => '<span class="label label-success gran">Siguiente →</span>'.html_safe %></span>
</div>
  <div class="conta2"><span class="label label-default gran">Bases_telas: <%= @bases_telas.count %></span></div>
</div>
<div class="peque">
<table class="table table-hover table-heading">
  <thead>
    <tr>
      <th class="cen">Clasificación</th>
      <th class="cen">Nombre</th>
      <th class="cen" colspan="3">Opciones</th>
    </tr>
  </thead>

  <tbody>
    <%= render @bases_telas %>
  </tbody>
</table>
</div>
<br>

<%= button_to 'Nueva base', new_bases_tela_path, class: "btn btn-success btn-lg", :method => "get", remote: true%>
</center>
<% else %>
<center>
    <div class="fadeIn derror">
    <%= image_tag ("error.png"), class: "img-rounded", height: '40', width: '40' %>
     <h1>Acceso denegado.</h1>
     <small>Por favor contáctese con el administrador.</small>
    </div>
  </center>
<% end %>