config/routes.rb
Rails.application.routes.draw do

  resources :colores

  resources :roles

  resources :user_sessions
  resources :users

  get 'login' => 'user_sessions#new', :as => :login
  get 'logout' => 'user_sessions#destroy', :as => :logout

  resources :articulos

  resources :videos

  resources :images

  resources :telas

  resources :telas do
    resources :images
  end
  
  resources :telas do
    resources :colores
  end

  resources :bases_telas

  resources :acabados

  resources :proveedores

  resources :clasificaciones

  get 'sofcartej/inicio'

  get 'sofcartej/sofcartej'

  get 'sofcartej/contacto'
  
  get 'sofcartej/pru'

  resources :tipos_telas

  resources :usos

  root 'sofcartej#inicio'

end

app/models/video.rb
class Video < ActiveRecord::Base
	validates :vid, presence: true
	validates :titulo, presence: true
  has_attached_file :vid
  do_not_validate_attachment_file_type :vid

  	def self.search(search, page)
		where(['upper(titulo) like ?',
		"%#{search}%".upcase]).paginate(page: page, per_page: 2).order("id")
	end
end

app/controllers/videos_controller.rb
class VideosController < ApplicationController
  before_action :set_video, only: [:show, :edit, :update, :destroy]
  skip_before_action :verify_authenticity_token
  before_filter :require_login, :except => [:index]
  # GET /videos
  # GET /videos.json
  def index
    @videos = Video.search(params[:search], params[:page])
  end

  # GET /videos/1
  # GET /videos/1.json
  def show
  end

  # GET /videos/new
  def new
    @video = Video.new
  end

  # GET /videos/1/edit
  def edit
  end

  # POST /videos
  # POST /videos.json
  def create
    @video = Video.new(video_params)
  respond_to do |format|
        if @video.save
          format.html { redirect_to videos_path}
          format.json { render :show, status: :created, location: @video }
        else
          format.html { render :new }
          format.json { render json: @video.errors, status: :unprocessable_entity }
        end
      end

  end

  # PATCH/PUT /videos/1
  # PATCH/PUT /videos/1.json
  def update
    respond_to do |format|
        if @video.update(video_params)
          format.html { redirect_to videos_path}
          format.json { render :show, status: :ok, location: @video }
        else
          format.html { render :edit }
          format.json { render json: @video.errors, status: :unprocessable_entity }
        end
      end
  end

  # DELETE /videos/1
  # DELETE /videos/1.json
  def destroy
    @video.destroy
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_video
      @video = Video.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def video_params
      params.require(:video).permit(:titulo, :vid)
    end
end

app/helpers/videos_helper.rb
module VideosHelper
end

app/views/videos/_form.html.erb
<%= simple_form_for(@video, :html => { :class => 'form-horizontal', remote: true } ) do |f| %>


  <div class="field">
    <%= f.label :titulo %><br>
    <%= f.text_field :titulo %>
  </div>
    <div class="field">
    <label>Video</label><br>
    <%= f.file_field :vid %>
  </div>
  <div class="actions">
    <%= f.submit "Guardar", class: "btn btn-success" %>
  </div>
<% end %>

app/views/videos/_video.html.erb
<div class="coni2">
     <div class="conit">
        <div class="btn-group">
          <a href="#"> </a>
          <ul class="list-inline">
          <% if current_user %>
          <% if current_user.role_id == 1 %>
            <li class="link"><%= link_to '<i class="fa fa-wrench txt-primary"></i><span> Editar</span>'.html_safe, edit_video_path(video), remote: true %>
            <% if video.id != 12 %></li>
              <li><%= link_to '<i class="fa fa-times txt-danger"></i><span> Eliminar</span>'.html_safe, video, method: :delete, data: { confirm: 'Are you sure?' }, remote: true %></li>
            <%end %>
            <% end %>
          <% end %>
          </ul>
        </div>
        <hr class="hr1"></div> <div class="ow-server">
        <%= video.titulo %>
        <%= video_tag(video.vid.url, height: '310', width: '480', controls: true) %>
        </div>
      </div>

app/views/videos/index.html.erb
<center>
<div class="bani">
  <h1 class="banih slideDown">Videos</h1>
  <%= image_tag("banner.jpg", class: "banii slideDown") %>
  <p class="banip slideDown"><br>Videos relacionados con la aplicación.</p>
</div>
  
  </center>
<% if current_user %>
<% if current_user.role_id == 1 %>
<%= button_to 'Nuevo Video', new_video_path, :method => "get", class: "btn btn-success", remote: true %>
<% end %>
<% end %>
<center>
<div class="convi">
<%= form_tag videos_path, :method => 'get' do %>
  <% content_tag :label do %>
    Buscar por Titulo:
    <%= text_field_tag :search, params[:search] %>
    <%= submit_tag "Buscar", :name => nil %>
  <% end %>
<% end %>
<div class="conpa">
<span class="label gran"><%= will_paginate @videos, :previous_label => '<span class="label label-success gran">← Anterior</span>'.html_safe, :next_label => '<span class="label label-success gran">Siguiente →</span>'.html_safe %></span>
</div>
<div class="conta2"><span class="label label-default gran">Videos: <%= @videos.count %></span></div>
</div>
<br>
<div class="conim2">
    <%= render @videos %>
</div>
<br>
</center>

app/views/videos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Titulo:</strong>
  <%= @video.titulo %>
</p>

<%= link_to 'Edit', edit_video_path(@video) %> |
<%= link_to 'Back', videos_path %>